### ISSUE TITLE
TODO: Use convergence method to isolate SSVEP

### ISSUE THREAD

**Issue by MusaMahmood** [MusaMahmood/SSVEP-Classification-MATLAB#2]
TODO: Use convergence method to isolate SSVEP over time. 
However, as there is not a fixed number of FFT points in PSD, this may be difficult.

**Comment by CaptainPotatoes** [comment]
Need some way to track 'peak rise'. But we need to look at peak ratio to other peaks. 
Also, put more emphasis on PSD, as it seems to be more accurate than FFT.
